name: Trigger workflow in test_sphinx to build documentation

on:
 push:
   branches:
     - main

jobs:
 trigger:
   runs-on: ubuntu-latest

   steps:
     - name: Trigger test_sphinx workflow by workflow_dispatch
       run: |
         curl -X POST -H "Authorization: token ${{ secrets.MY_PROJECT_PAT }}" \
         -H "Accept: application/vnd.github.everest-preview+json" \
         https://api.github.com/repos/MilanKlausz/test_sphinx/dispatches \
         -d '{"event_type": "test_sphinx_doc_push"}'
